export * from 'wechat-open-api'
export * from './wechat.interface'
export * from './app.module'
export * from './app.service'
export * from './official-account.module'
export * from './official-account.service'
export * from './pay.module'
export * from './pay.service'
